import type { Fortune } from '@/types/fortune';

export const MOCK_FORTUNES: Fortune[] = [
  {
    id: 'mock-taurus-20260711',
    date: '2026-07-11',
    zodiacId: 'taurus',
    zodiacJapanese: 'おうし座',
    zodiacKorean: '황소자리',
    rank: 1,
    originalText: '実力を発揮するチャンス。大胆なアクションが幸運のカギ。',
    readingText: 'じつりょくを はっきする チャンス。だいたんな アクションが こううんの カギ。',
    koreanTranslation: '실력을 발휘할 기회예요. 대담한 행동이 행운을 부르는 열쇠가 될 거예요.',
    luckyItem: 'スイーツ店',
    segments: [
      { text: '実力', vocabularyId: 'taurus-20260711-01' },
      { text: 'を', vocabularyId: null },
      { text: '発揮する', vocabularyId: 'taurus-20260711-02' },
      { text: 'チャンス。', vocabularyId: null },
      { text: '大胆な', vocabularyId: 'taurus-20260711-03' },
      { text: 'アクションが幸運のカギ。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'taurus-20260711-01', word: '実力', surfaceForm: '実力', reading: 'じつりょく', meaning: '실력' },
      { id: 'taurus-20260711-02', word: '発揮する', surfaceForm: '発揮する', reading: 'はっきする', meaning: '발휘하다' },
      { id: 'taurus-20260711-03', word: '大胆だ', surfaceForm: '大胆な', reading: 'だいたんだ', meaning: '대담하다' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-aries-20260711',
    date: '2026-07-11',
    zodiacId: 'aries',
    zodiacJapanese: 'おひつじ座',
    zodiacKorean: '양자리',
    rank: 2,
    originalText: '新しい出会いが運気を上げる。積極的に行動しよう。',
    readingText: 'あたらしい であいが うんきを あげる。せっきょくてきに こうどうしよう。',
    koreanTranslation: '새로운 만남이 운기를 높여줘요. 적극적으로 행동해 보세요.',
    luckyItem: 'カフェ',
    segments: [
      { text: '新しい', vocabularyId: 'aries-20260711-01' },
      { text: '出会い', vocabularyId: 'aries-20260711-02' },
      { text: 'が運気を上げる。', vocabularyId: null },
      { text: '積極的に', vocabularyId: 'aries-20260711-03' },
      { text: '行動しよう。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'aries-20260711-01', word: '新しい', surfaceForm: '新しい', reading: 'あたらしい', meaning: '새로운' },
      { id: 'aries-20260711-02', word: '出会い', surfaceForm: '出会い', reading: 'であい', meaning: '만남' },
      { id: 'aries-20260711-03', word: '積極的だ', surfaceForm: '積極的に', reading: 'せっきょくてきに', meaning: '적극적으로' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-leo-20260711',
    date: '2026-07-11',
    zodiacId: 'leo',
    zodiacJapanese: 'しし座',
    zodiacKorean: '사자자리',
    rank: 3,
    originalText: '創造力が高まる一日。自分らしさを大切にして。',
    readingText: 'そうぞうりょくが たかまる いちにち。じぶんらしさを たいせつに して。',
    koreanTranslation: '창의력이 높아지는 하루예요. 나다움을 소중히 여겨요.',
    luckyItem: 'アート系グッズ',
    segments: [
      { text: '創造力', vocabularyId: 'leo-20260711-01' },
      { text: 'が高まる一日。', vocabularyId: null },
      { text: '自分らしさ', vocabularyId: 'leo-20260711-02' },
      { text: 'を', vocabularyId: null },
      { text: '大切に', vocabularyId: 'leo-20260711-03' },
      { text: 'して。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'leo-20260711-01', word: '創造力', surfaceForm: '創造力', reading: 'そうぞうりょく', meaning: '창의력' },
      { id: 'leo-20260711-02', word: '自分らしさ', surfaceForm: '自分らしさ', reading: 'じぶんらしさ', meaning: '나다움' },
      { id: 'leo-20260711-03', word: '大切だ', surfaceForm: '大切に', reading: 'たいせつに', meaning: '소중히' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-gemini-20260711',
    date: '2026-07-11',
    zodiacId: 'gemini',
    zodiacJapanese: 'ふたご座',
    zodiacKorean: '쌍둥이자리',
    rank: 4,
    originalText: 'コミュニケーション力が光る日。話し合いが成功の鍵。',
    readingText: 'コミュニケーションりょくが ひかる ひ。はなしあいが せいこうの かぎ。',
    koreanTranslation: '소통 능력이 빛나는 날이에요. 대화가 성공의 열쇠예요.',
    luckyItem: '手帳',
    segments: [
      { text: 'コミュニケーション力が光る日。', vocabularyId: null },
      { text: '話し合い', vocabularyId: 'gemini-20260711-01' },
      { text: 'が', vocabularyId: null },
      { text: '成功', vocabularyId: 'gemini-20260711-02' },
      { text: 'の', vocabularyId: null },
      { text: '鍵', vocabularyId: 'gemini-20260711-03' },
      { text: '。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'gemini-20260711-01', word: '話し合い', surfaceForm: '話し合い', reading: 'はなしあい', meaning: '대화, 협의' },
      { id: 'gemini-20260711-02', word: '成功', surfaceForm: '成功', reading: 'せいこう', meaning: '성공' },
      { id: 'gemini-20260711-03', word: '鍵', surfaceForm: '鍵', reading: 'かぎ', meaning: '열쇠, 핵심' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-libra-20260711',
    date: '2026-07-11',
    zodiacId: 'libra',
    zodiacJapanese: 'てんびん座',
    zodiacKorean: '천칭자리',
    rank: 5,
    originalText: 'バランス感覚を活かして周囲と調和しよう。',
    readingText: 'バランスかんかくを いかして しゅういと ちょうわしよう。',
    koreanTranslation: '균형 감각을 살려 주변과 조화를 이뤄 보세요.',
    luckyItem: 'アロマキャンドル',
    segments: [
      { text: 'バランス感覚', vocabularyId: 'libra-20260711-01' },
      { text: 'を', vocabularyId: null },
      { text: '活かして', vocabularyId: 'libra-20260711-03' },
      { text: '周囲と', vocabularyId: null },
      { text: '調和', vocabularyId: 'libra-20260711-02' },
      { text: 'しよう。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'libra-20260711-01', word: 'バランス感覚', surfaceForm: 'バランス感覚', reading: 'バランスかんかく', meaning: '균형 감각' },
      { id: 'libra-20260711-02', word: '調和', surfaceForm: '調和', reading: 'ちょうわ', meaning: '조화' },
      { id: 'libra-20260711-03', word: '活かす', surfaceForm: '活かして', reading: 'いかして', meaning: '살려서' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-pisces-20260711',
    date: '2026-07-11',
    zodiacId: 'pisces',
    zodiacJapanese: 'うお座',
    zodiacKorean: '물고기자리',
    rank: 6,
    originalText: '直感を信じて行動すると良い結果が得られる。',
    readingText: 'ちょっかんを しんじて こうどうすると よい けっかが えられる。',
    koreanTranslation: '직감을 믿고 행동하면 좋은 결과를 얻을 수 있어요.',
    luckyItem: '海の見える場所',
    segments: [
      { text: '直感', vocabularyId: 'pisces-20260711-01' },
      { text: 'を信じて行動すると良い', vocabularyId: null },
      { text: '結果', vocabularyId: 'pisces-20260711-02' },
      { text: 'が', vocabularyId: null },
      { text: '得られる', vocabularyId: 'pisces-20260711-03' },
      { text: '。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'pisces-20260711-01', word: '直感', surfaceForm: '直感', reading: 'ちょっかん', meaning: '직감' },
      { id: 'pisces-20260711-02', word: '結果', surfaceForm: '結果', reading: 'けっか', meaning: '결과' },
      { id: 'pisces-20260711-03', word: '得る', surfaceForm: '得られる', reading: 'えられる', meaning: '얻다' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-aquarius-20260711',
    date: '2026-07-11',
    zodiacId: 'aquarius',
    zodiacJapanese: 'みずがめ座',
    zodiacKorean: '물병자리',
    rank: 7,
    originalText: '独創的なアイデアが周囲を驚かせる。自由に発想しよう。',
    readingText: 'どくそうてきな アイデアが しゅういを おどろかせる。じゆうに はっそうしよう。',
    koreanTranslation: '독창적인 아이디어가 주변을 놀라게 해요. 자유롭게 발상해 보세요.',
    luckyItem: '観葉植物',
    segments: [
      { text: '独創的な', vocabularyId: 'aquarius-20260711-01' },
      { text: 'アイデアが周囲を驚かせる。', vocabularyId: null },
      { text: '自由に', vocabularyId: 'aquarius-20260711-03' },
      { text: '発想', vocabularyId: 'aquarius-20260711-02' },
      { text: 'しよう。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'aquarius-20260711-01', word: '独創的だ', surfaceForm: '独創的な', reading: 'どくそうてきな', meaning: '독창적인' },
      { id: 'aquarius-20260711-02', word: '発想', surfaceForm: '発想', reading: 'はっそう', meaning: '발상' },
      { id: 'aquarius-20260711-03', word: '自由', surfaceForm: '自由に', reading: 'じゆうに', meaning: '자유롭게' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-sagittarius-20260711',
    date: '2026-07-11',
    zodiacId: 'sagittarius',
    zodiacJapanese: 'いて座',
    zodiacKorean: '사수자리',
    rank: 8,
    originalText: '遠出や旅行が吉。新しい刺激を求めて出かけよう。',
    readingText: 'とおでや りょこうが きち。あたらしい しげきを もとめて でかけよう。',
    koreanTranslation: '먼 곳 여행이 길해요. 새로운 자극을 찾아 떠나 보세요.',
    luckyItem: '旅行グッズ',
    segments: [
      { text: '遠出', vocabularyId: 'sagittarius-20260711-01' },
      { text: 'や旅行が吉。新しい', vocabularyId: null },
      { text: '刺激', vocabularyId: 'sagittarius-20260711-02' },
      { text: 'を求めて', vocabularyId: null },
      { text: '出かけよう', vocabularyId: 'sagittarius-20260711-03' },
      { text: '。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'sagittarius-20260711-01', word: '遠出', surfaceForm: '遠出', reading: 'とおで', meaning: '먼 나들이' },
      { id: 'sagittarius-20260711-02', word: '刺激', surfaceForm: '刺激', reading: 'しげき', meaning: '자극' },
      { id: 'sagittarius-20260711-03', word: '出かける', surfaceForm: '出かけよう', reading: 'でかけよう', meaning: '나가다' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-scorpio-20260711',
    date: '2026-07-11',
    zodiacId: 'scorpio',
    zodiacJapanese: 'さそり座',
    zodiacKorean: '전갈자리',
    rank: 9,
    originalText: '深い絆が運を引き寄せる。信頼できる人と過ごして。',
    readingText: 'ふかい きずなが うんを ひきよせる。しんらいできる ひとと すごして。',
    koreanTranslation: '깊은 인연이 운을 끌어당겨요. 믿을 수 있는 사람과 함께 지내세요.',
    luckyItem: 'ダークチョコレート',
    segments: [
      { text: '深い', vocabularyId: 'scorpio-20260711-01' },
      { text: '絆', vocabularyId: 'scorpio-20260711-02' },
      { text: 'が運を引き寄せる。', vocabularyId: null },
      { text: '信頼', vocabularyId: 'scorpio-20260711-03' },
      { text: 'できる人と過ごして。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'scorpio-20260711-01', word: '深い', surfaceForm: '深い', reading: 'ふかい', meaning: '깊은' },
      { id: 'scorpio-20260711-02', word: '絆', surfaceForm: '絆', reading: 'きずな', meaning: '인연, 유대' },
      { id: 'scorpio-20260711-03', word: '信頼', surfaceForm: '信頼', reading: 'しんらい', meaning: '신뢰' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-virgo-20260711',
    date: '2026-07-11',
    zodiacId: 'virgo',
    zodiacJapanese: 'おとめ座',
    zodiacKorean: '처녀자리',
    rank: 10,
    originalText: '細かい作業が得意な日。丁寧さが評価される。',
    readingText: 'こまかい さぎょうが とくいな ひ。ていねいさが ひょうかされる。',
    koreanTranslation: '세밀한 작업이 특기인 날이에요. 꼼꼼함이 인정받아요.',
    luckyItem: '文房具',
    segments: [
      { text: '細かい', vocabularyId: 'virgo-20260711-01' },
      { text: '作業が', vocabularyId: null },
      { text: '得意', vocabularyId: 'virgo-20260711-02' },
      { text: 'な日。', vocabularyId: null },
      { text: '丁寧さ', vocabularyId: 'virgo-20260711-03' },
      { text: 'が評価される。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'virgo-20260711-01', word: '細かい', surfaceForm: '細かい', reading: 'こまかい', meaning: '세밀한' },
      { id: 'virgo-20260711-02', word: '得意だ', surfaceForm: '得意', reading: 'とくい', meaning: '특기, 잘함' },
      { id: 'virgo-20260711-03', word: '丁寧だ', surfaceForm: '丁寧さ', reading: 'ていねいさ', meaning: '꼼꼼함' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-cancer-20260711',
    date: '2026-07-11',
    zodiacId: 'cancer',
    zodiacJapanese: 'かに座',
    zodiacKorean: '게자리',
    rank: 11,
    originalText: '家族や身近な人との時間を大切に。心が安らぐ日。',
    readingText: 'かぞくや みぢかな ひととの じかんを たいせつに。こころが やすらぐ ひ。',
    koreanTranslation: '가족이나 가까운 사람과의 시간을 소중히 여겨요. 마음이 편안해지는 날이에요.',
    luckyItem: '手作り料理',
    segments: [
      { text: '家族', vocabularyId: 'cancer-20260711-01' },
      { text: 'や', vocabularyId: null },
      { text: '身近な', vocabularyId: 'cancer-20260711-03' },
      { text: '人との時間を大切に。心が', vocabularyId: null },
      { text: '安らぐ', vocabularyId: 'cancer-20260711-02' },
      { text: '日。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'cancer-20260711-01', word: '家族', surfaceForm: '家族', reading: 'かぞく', meaning: '가족' },
      { id: 'cancer-20260711-02', word: '安らぐ', surfaceForm: '安らぐ', reading: 'やすらぐ', meaning: '편안해지다' },
      { id: 'cancer-20260711-03', word: '身近だ', surfaceForm: '身近な', reading: 'みぢかな', meaning: '가까운' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
  {
    id: 'mock-capricorn-20260711',
    date: '2026-07-11',
    zodiacId: 'capricorn',
    zodiacJapanese: 'やぎ座',
    zodiacKorean: '염소자리',
    rank: 12,
    originalText: '焦らず着実に進もう。努力が実を結ぶ時期が来る。',
    readingText: 'あせらず ちゃくじつに すすもう。どりょくが みを むすぶ じきが くる。',
    koreanTranslation: '서두르지 말고 착실하게 나아가요. 노력이 결실을 맺을 시기가 올 거예요.',
    luckyItem: '山の写真',
    segments: [
      { text: '焦らず', vocabularyId: 'capricorn-20260711-01' },
      { text: '着実に', vocabularyId: 'capricorn-20260711-02' },
      { text: '進もう。', vocabularyId: null },
      { text: '努力', vocabularyId: 'capricorn-20260711-03' },
      { text: 'が実を結ぶ時期が来る。', vocabularyId: null },
    ],
    vocabulary: [
      { id: 'capricorn-20260711-01', word: '焦る', surfaceForm: '焦らず', reading: 'あせらず', meaning: '서두르지 않고' },
      { id: 'capricorn-20260711-02', word: '着実だ', surfaceForm: '着実に', reading: 'ちゃくじつに', meaning: '착실하게' },
      { id: 'capricorn-20260711-03', word: '努力', surfaceForm: '努力', reading: 'どりょく', meaning: '노력' },
    ],
    sourceUrl: 'https://example.com',
    sourceDate: '2026-07-11',
    aiStatus: 'success',
  },
];

// zodiacId로 운세 찾기
export function getMockFortune(zodiacId: string): Fortune | undefined {
  return MOCK_FORTUNES.find((f) => f.zodiacId === zodiacId);
}

// 순위순으로 정렬된 목록 반환
export function getMockRanking() {
  return [...MOCK_FORTUNES].sort((a, b) => a.rank - b.rank);
}
